import { RushTimesConfiguration } from "./RushTimesConfiguration";

export type FeaturesContextType = {
  shadowVisible: boolean;
  setShadowVisible: React.Dispatch<React.SetStateAction<boolean>>;
  clock24Type: boolean;
  setClock24Type: React.Dispatch<React.SetStateAction<boolean>>;
  rushCoefficient: number;
  setRushCoefficient: React.Dispatch<React.SetStateAction<number>>;
  hideAdmin: boolean;
  setHideAdmin: React.Dispatch<React.SetStateAction<boolean>>;
  enableShadowClock: boolean;
  setEnableShadowClock: React.Dispatch<React.SetStateAction<boolean>>;
  linkHideAdmin: boolean;
  setLinkHideAdmin: React.Dispatch<React.SetStateAction<boolean>>;
  displayDigitalClock: boolean;
  setDisplayDigitalClock: React.Dispatch<React.SetStateAction<boolean>>;
  rushTimes: RushTimesConfiguration;
  setRushTimes: React.Dispatch<React.SetStateAction<RushTimesConfiguration>>;
  alarm: boolean;
  setAlarm: React.Dispatch<React.SetStateAction<boolean>>;
  alarmRinging: boolean;
  setAlarmRinging: React.Dispatch<React.SetStateAction<boolean>>;
  hueColor: number;
  setHueColor: React.Dispatch<React.SetStateAction<number>>;
  resetConfiguration: React.Dispatch<React.SetStateAction<void>>;
  alarmSound: HTMLAudioElement;
  startAlarm: React.Dispatch<React.SetStateAction<void>>;
  stopAlarm: React.Dispatch<React.SetStateAction<void>>;
  simulationClockSliderValue: number;
  setSimulationClockSliderValue: React.Dispatch<React.SetStateAction<number>>;
};
